# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

$rn_path = '../node_modules/react-native'

target 'BarTracker' do
  use_react_native!(
    :path => $rn_path,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  target 'BarTrackerTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      $rn_path,
      :mac_catalyst_enabled => false
    )
  end
end
